Exception in thread ray_import_thread:
Traceback (most recent call last):
  File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
    key = self.subscriber.poll()
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
    self._poll_locked(timeout=timeout)
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
    self._poll_request(), timeout=timeout
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
    (operations,), event_handler, self._context)
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
    _run_channel_spin_thread(state)
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
    channel_spin_thread.start()
  File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
  File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

[2m[36m(pid=90490)[0m Exception in thread ray_import_thread:
[2m[36m(pid=90490)[0m Traceback (most recent call last):
[2m[36m(pid=90490)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[2m[36m(pid=90490)[0m     self.run()
[2m[36m(pid=90490)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
[2m[36m(pid=90490)[0m     self._target(*self._args, **self._kwargs)
[2m[36m(pid=90490)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
[2m[36m(pid=90490)[0m     key = self.subscriber.poll()
[2m[36m(pid=90490)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
[2m[36m(pid=90490)[0m     self._poll_locked(timeout=timeout)
[2m[36m(pid=90490)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
[2m[36m(pid=90490)[0m     self._poll_request(), timeout=timeout
[2m[36m(pid=90490)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
[2m[36m(pid=90490)[0m     (operations,), event_handler, self._context)
[2m[36m(pid=90490)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
[2m[36m(pid=90490)[0m     _run_channel_spin_thread(state)
[2m[36m(pid=90490)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
[2m[36m(pid=90490)[0m     channel_spin_thread.start()
[2m[36m(pid=90490)[0m   File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
[2m[36m(pid=90490)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
[2m[36m(pid=90490)[0m     _start_new_thread(self._bootstrap, ())
[2m[36m(pid=90490)[0m RuntimeError: can't start new thread
[2m[36m(pid=90490)[0m 
[2m[36m(pid=90537)[0m Exception in thread ray_import_thread:
[2m[36m(pid=90537)[0m Traceback (most recent call last):
[2m[36m(pid=90537)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[2m[36m(pid=90537)[0m     self.run()
[2m[36m(pid=90537)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
[2m[36m(pid=90537)[0m     self._target(*self._args, **self._kwargs)
[2m[36m(pid=90537)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
[2m[36m(pid=90537)[0m     key = self.subscriber.poll()
[2m[36m(pid=90537)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
[2m[36m(pid=90537)[0m     self._poll_locked(timeout=timeout)
[2m[36m(pid=90537)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
[2m[36m(pid=90537)[0m     self._poll_request(), timeout=timeout
[2m[36m(pid=90537)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
[2m[36m(pid=90537)[0m     (operations,), event_handler, self._context)
[2m[36m(pid=90537)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
[2m[36m(pid=90537)[0m     _run_channel_spin_thread(state)
[2m[36m(pid=90537)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
[2m[36m(pid=90537)[0m     channel_spin_thread.start()
[2m[36m(pid=90537)[0m   File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
[2m[36m(pid=90537)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
[2m[36m(pid=90537)[0m     _start_new_thread(self._bootstrap, ())
[2m[36m(pid=90537)[0m RuntimeError: can't start new thread
[2m[36m(pid=90537)[0m 
[2m[36m(pid=90508)[0m Exception in thread ray_import_thread:
[2m[36m(pid=90508)[0m Traceback (most recent call last):
[2m[36m(pid=90508)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[2m[36m(pid=90508)[0m     self.run()
[2m[36m(pid=90508)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
[2m[36m(pid=90508)[0m     self._target(*self._args, **self._kwargs)
[2m[36m(pid=90508)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
[2m[36m(pid=90508)[0m     key = self.subscriber.poll()
[2m[36m(pid=90508)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
[2m[36m(pid=90508)[0m     self._poll_locked(timeout=timeout)
[2m[36m(pid=90508)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
[2m[36m(pid=90508)[0m     self._poll_request(), timeout=timeout
[2m[36m(pid=90508)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
[2m[36m(pid=90508)[0m     (operations,), event_handler, self._context)
[2m[36m(pid=90508)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
[2m[36m(pid=90508)[0m     _run_channel_spin_thread(state)
[2m[36m(pid=90508)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
[2m[36m(pid=90508)[0m     channel_spin_thread.start()
[2m[36m(pid=90508)[0m   File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
[2m[36m(pid=90508)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
[2m[36m(pid=90508)[0m     _start_new_thread(self._bootstrap, ())
[2m[36m(pid=90508)[0m RuntimeError: can't start new thread
[2m[36m(pid=90508)[0m 
[2m[36m(pid=90523)[0m Exception in thread ray_import_thread:
[2m[36m(pid=90523)[0m Traceback (most recent call last):
[2m[36m(pid=90523)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[2m[36m(pid=90523)[0m     self.run()
[2m[36m(pid=90523)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
[2m[36m(pid=90523)[0m     self._target(*self._args, **self._kwargs)
[2m[36m(pid=90523)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
[2m[36m(pid=90523)[0m     key = self.subscriber.poll()
[2m[36m(pid=90523)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
[2m[36m(pid=90523)[0m     self._poll_locked(timeout=timeout)
[2m[36m(pid=90523)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
[2m[36m(pid=90523)[0m     self._poll_request(), timeout=timeout
[2m[36m(pid=90523)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
[2m[36m(pid=90523)[0m     (operations,), event_handler, self._context)
[2m[36m(pid=90523)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
[2m[36m(pid=90523)[0m     _run_channel_spin_thread(state)
[2m[36m(pid=90523)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
[2m[36m(pid=90523)[0m     channel_spin_thread.start()
[2m[36m(pid=90523)[0m   File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
[2m[36m(pid=90523)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
[2m[36m(pid=90523)[0m     _start_new_thread(self._bootstrap, ())
[2m[36m(pid=90523)[0m RuntimeError: can't start new thread
[2m[36m(pid=90523)[0m 
[2m[36m(pid=90519)[0m Exception in thread ray_import_thread:
[2m[36m(pid=90519)[0m Traceback (most recent call last):
[2m[36m(pid=90519)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[2m[36m(pid=90519)[0m     self.run()
[2m[36m(pid=90519)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
[2m[36m(pid=90519)[0m     self._target(*self._args, **self._kwargs)
[2m[36m(pid=90519)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
[2m[36m(pid=90519)[0m     key = self.subscriber.poll()
[2m[36m(pid=90519)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
[2m[36m(pid=90519)[0m     self._poll_locked(timeout=timeout)
[2m[36m(pid=90519)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
[2m[36m(pid=90519)[0m     self._poll_request(), timeout=timeout
[2m[36m(pid=90519)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
[2m[36m(pid=90519)[0m     (operations,), event_handler, self._context)
[2m[36m(pid=90519)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
[2m[36m(pid=90519)[0m     _run_channel_spin_thread(state)
[2m[36m(pid=90519)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
[2m[36m(pid=90519)[0m     channel_spin_thread.start()
[2m[36m(pid=90519)[0m   File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
[2m[36m(pid=90519)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
[2m[36m(pid=90519)[0m     _start_new_thread(self._bootstrap, ())
[2m[36m(pid=90519)[0m RuntimeError: can't start new thread
[2m[36m(pid=90519)[0m 
[2m[36m(pid=90491)[0m Exception in thread ray_import_thread:
[2m[36m(pid=90491)[0m Traceback (most recent call last):
[2m[36m(pid=90491)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[2m[36m(pid=90491)[0m     self.run()
[2m[36m(pid=90491)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
[2m[36m(pid=90491)[0m     self._target(*self._args, **self._kwargs)
[2m[36m(pid=90491)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
[2m[36m(pid=90491)[0m     key = self.subscriber.poll()
[2m[36m(pid=90491)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
[2m[36m(pid=90491)[0m     self._poll_locked(timeout=timeout)
[2m[36m(pid=90491)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
[2m[36m(pid=90491)[0m     self._poll_request(), timeout=timeout
[2m[36m(pid=90491)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
[2m[36m(pid=90491)[0m     (operations,), event_handler, self._context)
[2m[36m(pid=90491)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
[2m[36m(pid=90491)[0m     _run_channel_spin_thread(state)
[2m[36m(pid=90491)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
[2m[36m(pid=90491)[0m     channel_spin_thread.start()
[2m[36m(pid=90491)[0m   File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
[2m[36m(pid=90491)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
[2m[36m(pid=90491)[0m     _start_new_thread(self._bootstrap, ())
[2m[36m(pid=90491)[0m RuntimeError: can't start new thread
[2m[36m(pid=90491)[0m 
[2m[36m(pid=90520)[0m Exception in thread ray_import_thread:
[2m[36m(pid=90520)[0m Traceback (most recent call last):
[2m[36m(pid=90520)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[2m[36m(pid=90520)[0m     self.run()
[2m[36m(pid=90520)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
[2m[36m(pid=90520)[0m     self._target(*self._args, **self._kwargs)
[2m[36m(pid=90520)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
[2m[36m(pid=90520)[0m     key = self.subscriber.poll()
[2m[36m(pid=90520)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
[2m[36m(pid=90520)[0m     self._poll_locked(timeout=timeout)
[2m[36m(pid=90520)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
[2m[36m(pid=90520)[0m     self._poll_request(), timeout=timeout
[2m[36m(pid=90520)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
[2m[36m(pid=90520)[0m     (operations,), event_handler, self._context)
[2m[36m(pid=90520)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
[2m[36m(pid=90520)[0m     _run_channel_spin_thread(state)
[2m[36m(pid=90520)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
[2m[36m(pid=90520)[0m     channel_spin_thread.start()
[2m[36m(pid=90520)[0m   File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
[2m[36m(pid=90520)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
[2m[36m(pid=90520)[0m     _start_new_thread(self._bootstrap, ())
[2m[36m(pid=90520)[0m RuntimeError: can't start new thread
[2m[36m(pid=90520)[0m 
[2m[36m(pid=90504)[0m Exception in thread ray_import_thread:
[2m[36m(pid=90504)[0m Traceback (most recent call last):
[2m[36m(pid=90504)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
[2m[36m(pid=90504)[0m     self.run()
[2m[36m(pid=90504)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 864, in run
[2m[36m(pid=90504)[0m     self._target(*self._args, **self._kwargs)
[2m[36m(pid=90504)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/import_thread.py", line 67, in _run
[2m[36m(pid=90504)[0m     key = self.subscriber.poll()
[2m[36m(pid=90504)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 410, in poll
[2m[36m(pid=90504)[0m     self._poll_locked(timeout=timeout)
[2m[36m(pid=90504)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/ray/_private/gcs_pubsub.py", line 266, in _poll_locked
[2m[36m(pid=90504)[0m     self._poll_request(), timeout=timeout
[2m[36m(pid=90504)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 976, in future
[2m[36m(pid=90504)[0m     (operations,), event_handler, self._context)
[2m[36m(pid=90504)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1306, in create
[2m[36m(pid=90504)[0m     _run_channel_spin_thread(state)
[2m[36m(pid=90504)[0m   File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
[2m[36m(pid=90504)[0m     channel_spin_thread.start()
[2m[36m(pid=90504)[0m   File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
[2m[36m(pid=90504)[0m   File "/home/rishabh/miniconda3/envs/comboptnet/lib/python3.6/threading.py", line 846, in start
[2m[36m(pid=90504)[0m     _start_new_thread(self._bootstrap, ())
[2m[36m(pid=90504)[0m RuntimeError: can't start new thread
[2m[36m(pid=90504)[0m 
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652928744 on cpu 6 ***
PC: @     0x7fe7453e2428  (unknown)  raise
    @     0x7fe745788390       3904  (unknown)
    @     0x7fe6e7352cb1         48  llvm::report_fatal_error()
    @     0x7fe6e72e4100         96  ReportErrnumFatal()
    @     0x7fe6e72e42f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7fe6e72e479d         48  llvm::thread::thread<>()
    @     0x7fe6e72e6871        144  llvm::ThreadPool::ThreadPool()
    @     0x7fe6e71fc74f        496  mlir::MLIRContext::MLIRContext()
    @     0x7fe6e71fca19        160  mlir::MLIRContext::MLIRContext()
    @     0x7fe6e4ed20cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7fe6e4ebe57a       4432  xla::TfrtCpuClient::Compile()
    @     0x7fe6e4dfd2b5        976  xla::PyClient::Compile()
    @     0x7fe6e4b67b5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7fe6e4b68434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7fe6e4b49821        544  pybind11::cpp_function::dispatcher()
    @     0x561a13e9d562  203712568  _PyCFunction_FastCallDict
    @     0x561a1400d660  (unknown)  (unknown)
[2022-05-19 08:22:24,158 E 75763 94761] logging.cc:325: *** SIGABRT received at time=1652928744 on cpu 6 ***
[2022-05-19 08:22:24,159 E 75763 94761] logging.cc:325: PC: @     0x7fe7453e2428  (unknown)  raise
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe745788390       3904  (unknown)
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe6e7352cb1         48  llvm::report_fatal_error()
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe6e72e4100         96  ReportErrnumFatal()
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe6e72e42f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe6e72e479d         48  llvm::thread::thread<>()
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe6e72e6871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe6e71fc74f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe6e71fca19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:22:24,162 E 75763 94761] logging.cc:325:     @     0x7fe6e4ed20cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:22:24,163 E 75763 94761] logging.cc:325:     @     0x7fe6e4ebe57a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:22:24,163 E 75763 94761] logging.cc:325:     @     0x7fe6e4dfd2b5        976  xla::PyClient::Compile()
[2022-05-19 08:22:24,163 E 75763 94761] logging.cc:325:     @     0x7fe6e4b67b5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:22:24,163 E 75763 94761] logging.cc:325:     @     0x7fe6e4b68434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:22:24,163 E 75763 94761] logging.cc:325:     @     0x7fe6e4b49821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:22:24,163 E 75763 94761] logging.cc:325:     @     0x561a13e9d562  203712568  _PyCFunction_FastCallDict
[2022-05-19 08:22:24,167 E 75763 94761] logging.cc:325:     @     0x561a1400d660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 434 in linear_jvp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 283 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 735 in broadcast_in_dim
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 3880 in expand_dims
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 1474 in expand_dims
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 5038 in _gather
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 5010 in _rewriting_take
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 533 in __getitem__
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/utils/comboptnet_utils.py", line 68 in signed_euclidean_distance_constraint_point
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/utils/comboptnet_utils.py", line 74 in check_point_feasibility
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 230 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
6.21user 2.40system 0:31.89elapsed 27%CPU (0avgtext+0avgdata 1995220maxresident)k
1888inputs+48outputs (0major+329851minor)pagefaults 0swaps
