WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652928718 on cpu 29 ***
PC: @     0x7fb18cfa3428  (unknown)  raise
    @     0x7fb18d349390       3904  (unknown)
    @     0x7fb12ef13cb1         48  llvm::report_fatal_error()
    @     0x7fb12eea5100         96  ReportErrnumFatal()
    @     0x7fb12eea52f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7fb12eea579d         48  llvm::thread::thread<>()
    @     0x7fb12eea7871        144  llvm::ThreadPool::ThreadPool()
    @     0x7fb12edbd74f        496  mlir::MLIRContext::MLIRContext()
    @     0x7fb12edbda19        160  mlir::MLIRContext::MLIRContext()
    @     0x7fb12ca930cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7fb12ca7f57a       4432  xla::TfrtCpuClient::Compile()
    @     0x7fb12c9be2b5        976  xla::PyClient::Compile()
    @     0x7fb12c728b5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7fb12c729434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7fb12c70a821        544  pybind11::cpp_function::dispatcher()
    @     0x557d53c64562  (unknown)  _PyCFunction_FastCallDict
    @     0x557d53dd4660  (unknown)  (unknown)
[2022-05-19 08:21:58,496 E 72032 75792] logging.cc:325: *** SIGABRT received at time=1652928718 on cpu 29 ***
[2022-05-19 08:21:58,497 E 72032 75792] logging.cc:325: PC: @     0x7fb18cfa3428  (unknown)  raise
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb18d349390       3904  (unknown)
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12ef13cb1         48  llvm::report_fatal_error()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12eea5100         96  ReportErrnumFatal()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12eea52f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12eea579d         48  llvm::thread::thread<>()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12eea7871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12edbd74f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12edbda19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12ca930cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12ca7f57a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12c9be2b5        976  xla::PyClient::Compile()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12c728b5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12c729434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x7fb12c70a821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:21:58,499 E 72032 75792] logging.cc:325:     @     0x557d53c64562  (unknown)  _PyCFunction_FastCallDict
[2022-05-19 08:21:58,502 E 72032 75792] logging.cc:325:     @     0x557d53dd4660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 316 in bitwise_not
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 515 in op
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 1529 in isclose
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 233 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
7.20user 2.12system 0:23.98elapsed 38%CPU (0avgtext+0avgdata 1995800maxresident)k
1888inputs+48outputs (0major+321210minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652929023 on cpu 42 ***
PC: @     0x7f14cb6d7428  (unknown)  raise
    @     0x7f14cba7d390       3872  (unknown)
    @     0x7f146d647cb1         48  llvm::report_fatal_error()
    @     0x7f146d5d9100         96  ReportErrnumFatal()
    @     0x7f146d5d92f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7f146d5d979d         48  llvm::thread::thread<>()
    @     0x7f146d5db871        144  llvm::ThreadPool::ThreadPool()
    @     0x7f146d4f174f        496  mlir::MLIRContext::MLIRContext()
    @     0x7f146d4f1a19        160  mlir::MLIRContext::MLIRContext()
    @     0x7f146b1c70cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7f146b1b357a       4432  xla::TfrtCpuClient::Compile()
    @     0x7f146b0f22b5        976  xla::PyClient::Compile()
    @     0x7f146ae5cb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7f146ae5d434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7f146ae3e821        544  pybind11::cpp_function::dispatcher()
    @     0x55ca8d9d2562  (unknown)  _PyCFunction_FastCallDict
    @     0x55ca8db42660  (unknown)  (unknown)
[2022-05-19 08:27:03,825 E 100471 102757] logging.cc:325: *** SIGABRT received at time=1652929023 on cpu 42 ***
[2022-05-19 08:27:03,825 E 100471 102757] logging.cc:325: PC: @     0x7f14cb6d7428  (unknown)  raise
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f14cba7d390       3872  (unknown)
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f146d647cb1         48  llvm::report_fatal_error()
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f146d5d9100         96  ReportErrnumFatal()
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f146d5d92f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f146d5d979d         48  llvm::thread::thread<>()
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f146d5db871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f146d4f174f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f146d4f1a19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:03,828 E 100471 102757] logging.cc:325:     @     0x7f146b1c70cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:27:03,829 E 100471 102757] logging.cc:325:     @     0x7f146b1b357a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:27:03,829 E 100471 102757] logging.cc:325:     @     0x7f146b0f22b5        976  xla::PyClient::Compile()
[2022-05-19 08:27:03,829 E 100471 102757] logging.cc:325:     @     0x7f146ae5cb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:27:03,829 E 100471 102757] logging.cc:325:     @     0x7f146ae5d434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:27:03,829 E 100471 102757] logging.cc:325:     @     0x7f146ae3e821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:27:03,829 E 100471 102757] logging.cc:325:     @     0x55ca8d9d2562  (unknown)  _PyCFunction_FastCallDict
[2022-05-19 08:27:03,833 E 100471 102757] logging.cc:325:     @     0x55ca8db42660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 340 in add
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 431 in fn
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 5869 in deferring_binary_op
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 225 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
5.98user 1.86system 0:23.01elapsed 34%CPU (0avgtext+0avgdata 1988860maxresident)k
0inputs+48outputs (0major+316677minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
