WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652928716 on cpu 63 ***
PC: @     0x7f6e79e59428  (unknown)  raise
    @     0x7f6e7a1ff390       3872  (unknown)
    @     0x7f6e1bdc9cb1         48  llvm::report_fatal_error()
    @     0x7f6e1bd5b100         96  ReportErrnumFatal()
    @     0x7f6e1bd5b2f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7f6e1bd5b79d         48  llvm::thread::thread<>()
    @     0x7f6e1bd5d871        144  llvm::ThreadPool::ThreadPool()
    @     0x7f6e1bc7374f        496  mlir::MLIRContext::MLIRContext()
    @     0x7f6e1bc73a19        160  mlir::MLIRContext::MLIRContext()
    @     0x7f6e199490cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7f6e1993557a       4432  xla::TfrtCpuClient::Compile()
    @     0x7f6e198742b5        976  xla::PyClient::Compile()
    @     0x7f6e195deb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7f6e195df434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7f6e195c0821        544  pybind11::cpp_function::dispatcher()
    @     0x55aa07b21562  377795096  _PyCFunction_FastCallDict
    @     0x55aa07c91660  (unknown)  (unknown)
[2022-05-19 08:21:56,100 E 72030 76852] logging.cc:325: *** SIGABRT received at time=1652928716 on cpu 63 ***
[2022-05-19 08:21:56,100 E 72030 76852] logging.cc:325: PC: @     0x7f6e79e59428  (unknown)  raise
[2022-05-19 08:21:56,104 E 72030 76852] logging.cc:325:     @     0x7f6e7a1ff390       3872  (unknown)
[2022-05-19 08:21:56,104 E 72030 76852] logging.cc:325:     @     0x7f6e1bdc9cb1         48  llvm::report_fatal_error()
[2022-05-19 08:21:56,104 E 72030 76852] logging.cc:325:     @     0x7f6e1bd5b100         96  ReportErrnumFatal()
[2022-05-19 08:21:56,104 E 72030 76852] logging.cc:325:     @     0x7f6e1bd5b2f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:21:56,104 E 72030 76852] logging.cc:325:     @     0x7f6e1bd5b79d         48  llvm::thread::thread<>()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e1bd5d871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e1bc7374f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e1bc73a19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e199490cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e1993557a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e198742b5        976  xla::PyClient::Compile()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e195deb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e195df434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x7f6e195c0821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:21:56,105 E 72030 76852] logging.cc:325:     @     0x55aa07b21562  377795096  _PyCFunction_FastCallDict
[2022-05-19 08:21:56,109 E 72030 76852] logging.cc:325:     @     0x55aa07c91660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 296 in abs
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 536 in absolute
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/utils/comboptnet_utils.py", line 51 in compute_delta_y
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 222 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
5.21user 1.66system 0:23.31elapsed 29%CPU (0avgtext+0avgdata 1981836maxresident)k
1888inputs+48outputs (0major+319584minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652929027 on cpu 29 ***
PC: @     0x7f5312386428  (unknown)  raise
    @     0x7f531272c390       3904  (unknown)
    @     0x7f52b42f6cb1         48  llvm::report_fatal_error()
    @     0x7f52b4288100         96  ReportErrnumFatal()
    @     0x7f52b42882f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7f52b428879d         48  llvm::thread::thread<>()
    @     0x7f52b428a871        144  llvm::ThreadPool::ThreadPool()
    @     0x7f52b41a074f        496  mlir::MLIRContext::MLIRContext()
    @     0x7f52b41a0a19        160  mlir::MLIRContext::MLIRContext()
    @     0x7f52b1e760cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7f52b1e6257a       4432  xla::TfrtCpuClient::Compile()
    @     0x7f52b1da12b5        976  xla::PyClient::Compile()
    @     0x7f52b1b0bb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7f52b1b0c434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7f52b1aed821        544  pybind11::cpp_function::dispatcher()
    @     0x5564a244f562  (unknown)  _PyCFunction_FastCallDict
    @     0x5564a25bf660  (unknown)  (unknown)
[2022-05-19 08:27:07,776 E 100467 107509] logging.cc:325: *** SIGABRT received at time=1652929027 on cpu 29 ***
[2022-05-19 08:27:07,776 E 100467 107509] logging.cc:325: PC: @     0x7f5312386428  (unknown)  raise
[2022-05-19 08:27:07,778 E 100467 107509] logging.cc:325:     @     0x7f531272c390       3904  (unknown)
[2022-05-19 08:27:07,778 E 100467 107509] logging.cc:325:     @     0x7f52b42f6cb1         48  llvm::report_fatal_error()
[2022-05-19 08:27:07,778 E 100467 107509] logging.cc:325:     @     0x7f52b4288100         96  ReportErrnumFatal()
[2022-05-19 08:27:07,778 E 100467 107509] logging.cc:325:     @     0x7f52b42882f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:27:07,778 E 100467 107509] logging.cc:325:     @     0x7f52b428879d         48  llvm::thread::thread<>()
[2022-05-19 08:27:07,778 E 100467 107509] logging.cc:325:     @     0x7f52b428a871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:27:07,778 E 100467 107509] logging.cc:325:     @     0x7f52b41a074f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:07,778 E 100467 107509] logging.cc:325:     @     0x7f52b41a0a19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:07,779 E 100467 107509] logging.cc:325:     @     0x7f52b1e760cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:27:07,779 E 100467 107509] logging.cc:325:     @     0x7f52b1e6257a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:27:07,779 E 100467 107509] logging.cc:325:     @     0x7f52b1da12b5        976  xla::PyClient::Compile()
[2022-05-19 08:27:07,779 E 100467 107509] logging.cc:325:     @     0x7f52b1b0bb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:27:07,779 E 100467 107509] logging.cc:325:     @     0x7f52b1b0c434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:27:07,779 E 100467 107509] logging.cc:325:     @     0x7f52b1aed821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:27:07,779 E 100467 107509] logging.cc:325:     @     0x5564a244f562  (unknown)  _PyCFunction_FastCallDict
[2022-05-19 08:27:07,781 E 100467 107509] logging.cc:325:     @     0x5564a25bf660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 320 in bitwise_and
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 515 in op
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 1527 in isclose
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/utils/comboptnet_utils.py", line 18 in softmin
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 322 in compute_constraints_mismatch_feasible
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 295 in compute_constraints_mismatch
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 246 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
7.72user 2.34system 0:26.95elapsed 37%CPU (0avgtext+0avgdata 1994380maxresident)k
0inputs+48outputs (0major+324796minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
