WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652928720 on cpu 35 ***
PC: @     0x7f4de45d0428  (unknown)  raise
    @     0x7f4de4976390       3872  (unknown)
    @     0x7f4d86540cb1         48  llvm::report_fatal_error()
    @     0x7f4d864d2100         96  ReportErrnumFatal()
    @     0x7f4d864d22f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7f4d864d279d         48  llvm::thread::thread<>()
    @     0x7f4d864d4871        144  llvm::ThreadPool::ThreadPool()
    @     0x7f4d863ea74f        496  mlir::MLIRContext::MLIRContext()
    @     0x7f4d863eaa19        160  mlir::MLIRContext::MLIRContext()
    @     0x7f4d840c00cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7f4d840ac57a       4432  xla::TfrtCpuClient::Compile()
    @     0x7f4d83feb2b5        976  xla::PyClient::Compile()
    @     0x7f4d83d55b5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7f4d83d56434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7f4d83d37821        544  pybind11::cpp_function::dispatcher()
    @     0x555df96d6562  571379416  _PyCFunction_FastCallDict
    @     0x555df9846660  (unknown)  (unknown)
[2022-05-19 08:22:00,499 E 72028 79907] logging.cc:325: *** SIGABRT received at time=1652928720 on cpu 35 ***
[2022-05-19 08:22:00,500 E 72028 79907] logging.cc:325: PC: @     0x7f4de45d0428  (unknown)  raise
[2022-05-19 08:22:00,510 E 72028 79907] logging.cc:325:     @     0x7f4de4976390       3872  (unknown)
[2022-05-19 08:22:00,510 E 72028 79907] logging.cc:325:     @     0x7f4d86540cb1         48  llvm::report_fatal_error()
[2022-05-19 08:22:00,510 E 72028 79907] logging.cc:325:     @     0x7f4d864d2100         96  ReportErrnumFatal()
[2022-05-19 08:22:00,510 E 72028 79907] logging.cc:325:     @     0x7f4d864d22f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:22:00,510 E 72028 79907] logging.cc:325:     @     0x7f4d864d279d         48  llvm::thread::thread<>()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d864d4871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d863ea74f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d863eaa19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d840c00cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d840ac57a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d83feb2b5        976  xla::PyClient::Compile()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d83d55b5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d83d56434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x7f4d83d37821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:22:00,511 E 72028 79907] logging.cc:325:     @     0x555df96d6562  571379416  _PyCFunction_FastCallDict
[2022-05-19 08:22:00,515 E 72028 79907] logging.cc:325:     @     0x555df9846660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 434 in linear_jvp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 283 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 102 in neg
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 410 in <lambda>
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 493 in __neg__
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 320 in compute_constraints_mismatch_feasible
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 295 in compute_constraints_mismatch
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 246 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
7.94user 1.92system 0:27.35elapsed 36%CPU (0avgtext+0avgdata 1987876maxresident)k
1888inputs+48outputs (0major+319751minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
*** SIGABRT received at time=1652929027 on cpu 42 ***
PC: @     0x7f12d9f28428  (unknown)  raise
    @     0x7f12da2ce390       3872  (unknown)
    @     0x7f127be98cb1         48  llvm::report_fatal_error()
    @     0x7f127be2a100         96  ReportErrnumFatal()
    @     0x7f127be2a2f8        128  llvm::llvm_execute_on_thread_impl()
    @     0x7f127be2a79d         48  llvm::thread::thread<>()
    @     0x7f127be2c871        144  llvm::ThreadPool::ThreadPool()
    @     0x7f127bd4274f        496  mlir::MLIRContext::MLIRContext()
    @     0x7f127bd42a19        160  mlir::MLIRContext::MLIRContext()
    @     0x7f1279a180cc       2528  xla::cpu::CpuCompiler::RunBackend()
    @     0x7f1279a0457a       4432  xla::TfrtCpuClient::Compile()
    @     0x7f12799432b5        976  xla::PyClient::Compile()
    @     0x7f12796adb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
    @     0x7f12796ae434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
    @     0x7f127968f821        544  pybind11::cpp_function::dispatcher()
    @     0x55e82115b562  265548632  _PyCFunction_FastCallDict
    @     0x55e8212cb660  (unknown)  (unknown)
[2022-05-19 08:27:07,783 E 100468 109158] logging.cc:325: *** SIGABRT received at time=1652929027 on cpu 42 ***
[2022-05-19 08:27:07,783 E 100468 109158] logging.cc:325: PC: @     0x7f12d9f28428  (unknown)  raise
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f12da2ce390       3872  (unknown)
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f127be98cb1         48  llvm::report_fatal_error()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f127be2a100         96  ReportErrnumFatal()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f127be2a2f8        128  llvm::llvm_execute_on_thread_impl()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f127be2a79d         48  llvm::thread::thread<>()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f127be2c871        144  llvm::ThreadPool::ThreadPool()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f127bd4274f        496  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f127bd42a19        160  mlir::MLIRContext::MLIRContext()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f1279a180cc       2528  xla::cpu::CpuCompiler::RunBackend()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f1279a0457a       4432  xla::TfrtCpuClient::Compile()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f12799432b5        976  xla::PyClient::Compile()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f12796adb5c       1632  pybind11::detail::argument_loader<>::call_impl<>()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f12796ae434        192  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x7f127968f821        544  pybind11::cpp_function::dispatcher()
[2022-05-19 08:27:07,786 E 100468 109158] logging.cc:325:     @     0x55e82115b562  265548632  _PyCFunction_FastCallDict
[2022-05-19 08:27:07,789 E 100468 109158] logging.cc:325:     @     0x55e8212cb660  (unknown)  (unknown)
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 360 in backend_compile
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 297 in xla_primitive_callable
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 179 in cached
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/util.py", line 186 in wrapper
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/xla.py", line 248 in apply_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 603 in process_primitive
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/core.py", line 264 in bind
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/lax/lax.py", line 390 in ne
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 2001 in isnan
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 1537 in isclose
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 233 in mismatch_function
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/linear_util.py", line 166 in call_wrapped
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 505 in trace_to_jaxpr
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 102 in linearize
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/interpreters/ad.py", line 115 in vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 1997 in _vjp
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 901 in value_and_grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/api.py", line 829 in grad_f
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/jax/_src/traceback_util.py", line 183 in reraise_with_filtered_traceback
  File "/home/rishabh/btp/src/CombOptNet/ext/CombOptNetJAX/models/comboptnet.py", line 123 in backward
  File "/home/rishabh/.local/share/virtualenvs/CombOptNetJAX-wSKOtHoc/lib/python3.6/site-packages/torch/autograd/function.py", line 77 in apply
Command terminated by signal 6
7.61user 1.96system 0:27.02elapsed 35%CPU (0avgtext+0avgdata 1982808maxresident)k
0inputs+48outputs (0major+326452minor)pagefaults 0swaps
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
